# -*- coding: utf-8 -*-
"""Task07_2025.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13zP7djRTBeG5tsTNq-mV-TGtIeDmqV7W

**Task 07: Querying RDF(s)**
"""

import urllib.request
from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS

# Download the validator helper if not present (harmless if already exists)
url = 'https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/refs/heads/master/Assignment4/course_materials/python/validation.py'
urllib.request.urlretrieve(url, 'validation.py')
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2025-2026/master/Assignment4/course_materials"

from validation import Report

# Create graph and load data
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.parse(github_storage+"/rdf/data06.ttl", format="TTL")
report = Report()

"""**TASK 7.1a: For all classes, list each classURI. If the class belogs to another class, then list its superclass.**
**Do the exercise in RDFLib returning a list of Tuples: (class, superclass) called "result". If a class does not have a super class, then return None as the superclass**
"""

# Get all classes and their superclasses (RDFLib)
result = []  # list of tuples (class, superclass or None)
classes = set()
for s in g.subjects(RDF.type, RDFS.Class):
  classes.add(s)
for c in classes:
  sc = g.value(subject=c, predicate=RDFS.subClassOf)
  result.append((c, sc))

for r in result:
  print(r)

## Validation: Do not remove
report.validate_07_1a(result)

"""**TASK 7.1b: Repeat the same exercise in SPARQL, returning the variables ?c (class) and ?sc (superclass)**"""

query = """PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?c ?sc
WHERE {
  ?c a rdfs:Class .
  OPTIONAL { ?c rdfs:subClassOf ?sc }
}
"""

for r in g.query(query):
  print(r.c, r.sc)

## Validation: Do not remove
report.validate_07_1b(query, g)

"""**TASK 7.2a: List all individuals of "Person" with RDFLib (remember the subClasses). Return the individual URIs in a list called "individuals"**

"""

ns = Namespace("http://oeg.fi.upm.es/def/people#")

# variable to return
individuals = []

# Get all Person subclasses (recursively) and collect individuals
def get_all_subclasses(graph, parent):
  subs = []
  for s in graph.subjects(RDFS.subClassOf, parent):
    subs.append(s)
    subs.extend(get_all_subclasses(graph, s))
  return subs

person_class = ns.Person
person_types = [person_class] + get_all_subclasses(g, person_class)
for t in person_types:
  for inst in g.subjects(RDF.type, t):
    individuals.append(inst)

for i in individuals:
  print(i)

# validation. Do not remove
report.validate_07_02a(individuals)

"""**TASK 7.2b: Repeat the same exercise in SPARQL, returning the individual URIs in a variable ?ind**"""

query = """PREFIX ontology: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?ind
WHERE {
  ?ind a ?type .
  ?type rdfs:subClassOf* ontology:Person .
}
"""

for r in g.query(query):
  print(r.ind)

## Validation: Do not remove
report.validate_07_02b(g, query)

"""**TASK 7.3:  List the name and type of those who know Rocky (in SPARQL only). Use name and type as variables in the query**"""

query = """PREFIX ontology: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name ?type
WHERE {
  ?ind ontology:knows ontology:Rocky .
  ?ind rdfs:label ?name .
  ?ind a ?type .
}
"""

# Visualize the results
for r in g.query(query):
  print(r.name, r.type)

## Validation: Do not remove
report.validate_07_03(g, query)

## Validation: Do not remove
report.validate_07_03(g, query)

"""**Task 7.4: List the name of those entities who have a colleague with a dog, or that have a collegue who has a colleague who has a dog (in SPARQL). Return the results in a variable called name**"""

query = """PREFIX ontology: <http://oeg.fi.upm.es/def/people#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?name
WHERE {
  {
    ?ind ontology:hasColleague ?colleague .
    ?colleague ontology:ownsPet ?pet .
    ?pet a ontology:Animal .
    ?ind rdfs:label ?name .
  } UNION {
    ?ind ontology:hasColleague ?colleague .
    ?colleague ontology:hasColleague ?colleague2 .
    ?colleague2 ontology:ownsPet ?pet .
    ?pet a ontology:Animal .
    ?ind rdfs:label ?name .
  }
}
"""

for r in g.query(query):
  print(r.name)

## Validation: Do not remove
report.validate_07_04(g,query)
report.save_report("_Task_07")